gmail:
  Client: Client
  Prospect: Prospect
  Facture: Facture
  Administratif: Administratif
  Newsletter: Newsletter
  Spam: Spam
  À vérifier: À vérifier
hotmail:
  Client: Client
  Prospect: Prospect
  Facture: Facture
  Administratif: Administratif
  Newsletter: Newsletter
  Spam: Spam
  À vérifier: À vérifier
