gmail:
  "[Imap]/Drafts": "[Imap]/Drafts"
  À répondre: À répondre
  À traiter: À traiter
  Commentaire: Commentaire
  En attente de réponse: En attente de réponse
  FYI: FYI
  Marketing: Marketing
  Mise à jour de réunion: Mise à jour de réunion
  Newsletter: Newsletter
  Notification: Notification
  Relance: Relance
  Traité: Traité
hotmail:
  "[Imap]/Drafts": "[Imap]/Drafts"
  À répondre: À répondre
  À traiter: À traiter
  Commentaire: Commentaire
  En attente de réponse: En attente de réponse
  FYI: FYI
  Marketing: Marketing
  Mise à jour de réunion: Mise à jour de réunion
  Newsletter: Newsletter
  Notification: Notification
  Relance: Relance
  Traité: Traité
