gmail:
  À traiter: À traiter
  À répondre: À répondre
  Relance: Relance
  Commentaire: Commentaire
  FYI: FYI
  Notification: Notification
  Mise à jour de réunion: Mise à jour de réunion
  Newsletter: Newsletter
  Marketing: Marketing
  Traité: Traité
  En attente de réponse: En attente de réponse
hotmail:
  À traiter: À traiter
  À répondre: À répondre
  Relance: Relance
  Commentaire: Commentaire
  FYI: FYI
  Notification: Notification
  Mise à jour de réunion: Mise à jour de réunion
  Newsletter: Newsletter
  Marketing: Marketing
  Traité: Traité
  En attente de réponse: En attente de réponse
